---
- hosts: controller
  serial: 1
  tasks:
  - name: Reboot
    command: shutdown -r now
    async: 0
    poll: 0
    failed_when: false

  - name: waiting for server to come back
    wait_for: host={{ inventory_hostname }}
              state=started
              connect_timeout=60
              timeout=900
    delegate_to: localhost
    become: false

  - name: cluster health check
    command: /etc/sensu/plugins/percona-cluster-size.rb -d /root/.my.cnf --expected 3 --criticality critical
    register: cstat
    until: cstat | succeeded
    retries: 5
    wait_for: delay=10
    run_once: true

- hosts: compute:!controller
  serial: 1
  tasks:
  - name: Reboot
    command: shutdown -r now
    async: 0
    poll: 0
    failed_when: false

  - name: waiting for server to come back
    wait_for: host={{ inventory_hostname }}
              state=started
              connect_timeout=60
              timeout=900
    delegate_to: localhost
    become: false

  - name: check nova services
    command: /etc/sensu/plugins/check-nova-services.sh
    register: result
    until: result | succeeded
    retries: 5
    wait_for: delay=10
    delegate_to: "{{ groups['controller']|first }}"

  - name: check neutron agents
    command: /etc/sensu/plugins/check-neutron-agents.sh
    register: result
    until: result | succeeded
    retries: 5
    wait_for: delay=10

  - name: cluster health check on db_arbiter
    command: /etc/sensu/plugins/percona-cluster-size.rb -d /root/.my.cnf --expected 3 --criticality critical
    register: cstat
    until: cstat | succeeded
    retries: 5
    wait_for: delay=10
    delegate_to: "{{ groups['controller']|first }}"
    when: inventory_hostname in groups['db_arbiter']

- hosts: swiftnode
  serial: 1
  tasks:
  - name: Reboot
    command: shutdown -r now
    async: 0
    poll: 0
    failed_when: false

  - name: waiting for server to come back
    wait_for: host={{ inventory_hostname }}
              state=started
              connect_timeout=60
              timeout=900
    delegate_to: localhost
    become: false

  - name: swift health check
    command: /etc/sensu/plugins/check-swift-dispersion.py
    register: result
    until: result | succeeded
    retries: 5
    wait_for: delay=10

- hosts: ceph_osds[0]
  tasks:
  - name: ceph health check before starting reboots
    command: /etc/sensu/plugins/check-ceph.rb
    register: result
    until: result | succeeded
    retries: 5
    wait_for: delay=10

- hosts: ceph_osds
  serial: 1
  tasks:
  - name: set noout flag
    command: ceph osd set noout

  - name: Reboot
    command: shutdown -r now
    async: 0
    poll: 0
    failed_when: false

  - name: waiting for server to come back
    wait_for: host={{ inventory_hostname }}
              state=started
              connect_timeout=60
              timeout=900
    delegate_to: localhost
    become: false

  - name: unset noout flag
    command: ceph osd unset noout

  - name: wait for noout flag
    pause: seconds=30

  - name: ceph health check
    command: /etc/sensu/plugins/check-ceph.rb
    register: result
    until: result | succeeded
    retries: 5
    wait_for: delay=10

- hosts: ceph_monitors
  serial: 1
  tasks:
  - name: Reboot
    command: shutdown -r now
    async: 0
    poll: 0
    failed_when: false

  - name: waiting for server to come back
    wait_for: host={{ inventory_hostname }}
              state=started
              connect_timeout=60
              timeout=900
    delegate_to: localhost
    become: false

  - name: ceph health check
    command: /etc/sensu/plugins/check-ceph.rb
    register: result
    until: result | succeeded
    retries: 5
    wait_for: delay=10
